name: Release Project

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package project
        run: tar -zcf ssl-metrics-pipeline.tar.gz --exclude="env" --exclude=".github" --exclude=".git" .

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: *.tar.gz
